### ISSUE TITLE
Maven url  连不通啊

### ISSUE THREAD

**Issue by leeyuanhe** [cuisongliu/mybatis_generator_gradle_plugin#1]
![image](https://user-images.githubusercontent.com/17116084/30331175-a3139c40-9809-11e7-80b7-2814b4516bf6.png)

**Comment by cuisongliu** [comment]
https://plugins.gradle.org/plugin/com.cuisongliu.plugin.mybatis-generator   ,你看这里能连通不，因为是墙外，可能有点不太稳定。

**Comment by leeyuanhe** [comment]
@cuisongliu  这个gradle的插件介绍页是可以访问的，但是https://plugins.gradle.org/m2/ 就不行

**Comment by cuisongliu** [comment]
你把你的gradle配置贴一下，以及gradle版本，是以插件的形式引入的吧。不行你看下 https://github.com/cuisongliu/springboot-integration 我的这个项目已经集成了，你把module那块看看怎么配置,如果按照我介绍的配置应该没有问题，我这用的gradle版本是3.3 是否gradle版本过低。

**Comment by leeyuanhe** [comment]
配置就是按照那个介绍页上配的,后来没整这个集成了,直接用Mabatis-generate 生成了，不过还是谢谢了

**Comment by cuisongliu** [comment]
@leeyuanhe  好像是我首页的那个地址有问题 你重新配置一下就好了，是我中央仓库的地址写错了 不好意思。
